spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate            # never auto-create in prod
    show-sql: false

logging:
  level:
    com.ani.pm: INFO